config/routes.rb
Rails.application.routes.draw do
  get 'courses/import', to: 'courses#import', as: 'courses_import'
  get 'students/import', to: 'students#import', as: 'import_students'
  get 'instructors/import', to: 'instructors#import', as: 'instructors_import'
  get 'colleges/import', to: 'colleges#import', as: 'colleges_import'
  get 'high_schools/import', to: 'high_schools#import', as: 'high_schools_import'

  post '/courses(.:format)', to: 'courses#to_db', as: 'course_to_db'
  post '/students(.:format)', to: 'students#to_db', as: 'student_to_db'
  post '/instructors(.:format)', to: 'instructors#to_db', as: 'instructor_to_db'
  post '/colleges(.:format)', to: 'colleges#to_db', as: 'college_to_db'
  post '/high_schools(.:format)', to: 'high_schools#to_db', as: 'high_school_to_db'
  
  get '/courses/stats', to: 'courses#stat', as: 'courses_stat'
  
  get '/student/courses/:id', to: 'students#course', as: 'student_courses'
  get 'course/:id', to: 'courses#more', as: 'more'

  
  devise_for :users
  resources :course_students
  resources :colleges
  resources :high_schools
  resources :instructors
  resources :states
  resources :statistics
  resources :students
  resources :courses

  get 'reports/students/attempts', to: 'student_reports#attempts', as: 'attempt_report'
  get 'users', to: 'users#index', as: 'admin_users'
  root to: 'test#index'
end

app/models/student.rb
class Student < ApplicationRecord
  validates_uniqueness_of :uid

	has_many :course_students
	has_many :courses, through: :course_students

	def self.search(search)
		where("uid LIKE ? OR degree LIKE ? OR email LIKE ? OR fname LIKE ? OR lname LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  require 'csv'
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all.paginate(:page => params[:page])
    if params[:search]
      @students = Student.search(params[:search]).order("created_at DESC")
    else
      @students = Student.all.order("created_at DESC")
    end
  end

  def import

  end

  def to_db
    student = Student.new();
    added_rows = 0
    rows = 0
    CSV.foreach(params[:file].path, :headers => true) do |row|
      data = row.to_hash
      student = Student.new(
                            :lname => (data['Last Name']),
                            :fname => (data['First Name']),
                            :uid => (data['UID']),
                            :transfer_hours => (data['TREH']).to_i,
      )
      student.save
      #course = Course.find_by(course_number: (data['Number']).to_i)
      course = Course.find_by_course_number_and_term((data['Number']).to_i, (data['Term']).to_i)
      #course = Course.new(:
      student = Student.find_by(uid: (data['UID']))
      if not student.courses.include?(course)
        student.courses << course
        relation = student.course_students.find_by(course: course) 
        if not data['Grade'].blank?
          relation.grade = data['Grade']
        end
        @courses = Course.where(course_number: (data['Number']).to_i)
        @courses.each do |c|
          if student.courses.include?(c)
            newrelation = student.course_students.find_by(course: c)
            if (relation.grade == "D" or relation.grade == "D+" or relation.grade == "F" or relation.grade == "U")
              newrelation.increment
              newrelation.save
            end
            relation.attempt = newrelation.attempt
          end
        end
        relation.save
      end
      
      student.save
    end
    redirect_to students_path
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def course
    @courses = CourseStudent.where(student_id: params[:id])
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:uid, :act_math, :degree, :email, :ethnicity, :fname, :gender, :graduation, :high_school, :lname, :prior_college, :transfer_hours)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
  def course_name(id)
    return 'CHEM '  + Course.find(id.to_i).course_number.to_s
  end
end

app/views/students/_form.html.erb
<%= form_for(student) do |f| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :uid %>
    <%= f.text_field :uid, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :act_math %>
    <%= f.number_field :act_math, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :degree %>
    <%= f.text_field :degree, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :ethnicity %>
    <%= f.text_field :ethnicity, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :fname %>
    <%= f.text_field :fname, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :gender %>
    <%= f.text_field :gender, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :graduation %>
    <%= f.date_select :graduation, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :high_school %>
    <%= f.number_field :high_school, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :lname %>
    <%= f.text_field :lname, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :prior_college %>
    <%= f.number_field :prior_college, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :transfer_hours %>
    <%= f.number_field :transfer_hours, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/course.html.erb
<div class="col-md-12">
  <h1></h1>
  <% @courses.each do |course| %>
      <p><%= course_name(course.course_id) %></p>
  <% end %>
</div>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/import.html.erb
<%= form_tag({:action => :to_db}, multipart: true, class: 'form') do %>
    <div class="field form-group">
      <%= file_field_tag :file, class: 'form-control' %>
      <%= submit_tag( "Import", class: 'form-control' ) %>
    </div>
<% end %>

app/views/students/index.html.erb
<div class="col-md-12">
  <p id="notice"><%= notice %></p>
  <div class="row top_tiles">
    <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
      <div class="tile-stats">
        <div class="icon"><i class="fa fa-caret-square-o-right"></i></div>
        <div class="count"><%= @students.count %></div>
        <h3>Number Students </h3>
        <p>Lorem ipsum psdea itgum rixt.</p>
      </div>
    </div>

    <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
      <div class="tile-stats">
        <div class="icon"><i class="fa fa-caret-square-o-right"></i></div>
        <div class="count"><%= @students.count %></div>
        <h3>Average Act </h3>
        <p>Lorem ipsum psdea itgum rixt.</p>
      </div>
    </div>

    <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
      <div class="tile-stats">
        <div class="icon"><i class="fa fa-caret-square-o-right"></i></div>
        <div class="count"><%= @students.count %></div>
        <h3>Males </h3>
        <p>Lorem ipsum psdea itgum rixt.</p>
      </div>
    </div>

    <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
      <div class="tile-stats">
        <div class="icon"><i class="fa fa-caret-square-o-right"></i></div>
        <div class="count"><%= @students.count %></div>
        <h3>Females </h3>
        <p>Lorem ipsum psdea itgum rixt.</p>
      </div>
    </div>

  </div>

  <h1>Students</h1>

  <%= form_tag(students_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Students" %>
  <%= submit_tag "Search", :name => nil %>
  <% end %>
  <% if @students.blank? %>
  <h4>There are no students containing the term <%= params[:search] %>.</h4>
  <% end %>

  <table class="table table-striped table-responsive">
    <thead>
    <tr>
      <th>Uid</th>
      <th>Fname</th>
      <th>Lname</th>
      <th>Transfer hours</th>
      <th>Taking, failed attempts, grade</th>
      <th colspan="3">options</th>
    </tr>
    </thead>

    <tbody>
    <% @students.each do |student| %>
        <tr>
          <td><%= student.uid %></td>
          <td><%=  link_to student.fname, student_courses_path(student.id) %></td>
          <td><%= student.lname %></td>
          <td><%= student.transfer_hours %></td>
          <td>
          <% student.course_students.each do |coursestudent| %>
            <%= coursestudent.course.course_number%>, <%=coursestudent.attempt%>, <%=coursestudent.grade%>
          <% end %>
          </td>
          <td><%= link_to 'Edit', edit_student_path(student) %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
  <br>

  <%= link_to 'New Student', new_student_path %>

</div>

app/views/students/new.html.erb
<div class="col-md-12">
  <h1>New Student</h1>

  <%= render 'form', student: @student %>

  <%= link_to 'Back', students_path %>
</div>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uid:</strong>
  <%= @student.uid %>
</p>

<p>
  <strong>Act math:</strong>
  <%= @student.act_math %>
</p>

<p>
  <strong>Degree:</strong>
  <%= @student.degree %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Ethnicity:</strong>
  <%= @student.ethnicity %>
</p>

<p>
  <strong>Fname:</strong>
  <%= @student.fname %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @student.gender %>
</p>

<p>
  <strong>Graduation:</strong>
  <%= @student.graduation %>
</p>

<p>
  <strong>High school:</strong>
  <%= @student.high_school %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @student.lname %>
</p>

<p>
  <strong>Prior college:</strong>
  <%= @student.prior_college %>
</p>

<p>
  <strong>Transfer hours:</strong>
  <%= @student.transfer_hours %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>