config/routes.rb
Rails.application.routes.draw do
  get 'courses/import', to: 'courses#import', as: 'courses_import'
  get 'students/import', to: 'students#import', as: 'import_students'
  get 'instructors/import', to: 'instructors#import', as: 'instructors_import'
  get 'colleges/import', to: 'colleges#import', as: 'colleges_import'
  get 'high_schools/import', to: 'high_schools#import', as: 'high_schools_import'

  post '/courses(.:format)', to: 'courses#to_db', as: 'course_to_db'
  post '/students(.:format)', to: 'students#to_db', as: 'student_to_db'
  post '/instructors(.:format)', to: 'instructors#to_db', as: 'instructor_to_db'
  post '/colleges(.:format)', to: 'colleges#to_db', as: 'college_to_db'
  post '/high_schools(.:format)', to: 'high_schools#to_db', as: 'high_school_to_db'
  
  get '/courses/stats', to: 'courses#stat', as: 'courses_stat'
  
  get '/student/courses/:id', to: 'students#course', as: 'student_courses'
  get 'course/:id', to: 'courses#more', as: 'more'

  
  devise_for :users
  resources :course_students
  resources :colleges
  resources :high_schools
  resources :instructors
  resources :states
  resources :statistics
  resources :students
  resources :courses

  get 'reports/students/attempts', to: 'student_reports#attempts', as: 'attempt_report'
  get 'users', to: 'users#index', as: 'admin_users'
  root to: 'test#index'
end

app/models/instructor.rb
class Instructor < ApplicationRecord
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  require 'csv'
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]

  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = Instructor.all
  end

  def import
  end

  def to_db
    instructor = Instructor.new()
    added_rows = 0
    rows=0
    CSV.foreach(params[:file].path, :headers => true) do |row|
      data = row.to_hash
      
      instructor = Instructor.new(
                         :name => data['Name']
      )
      if instructor.save
        added_rows = added_rows + 1
      end
      rows = rows + 1
    end
    if added_rows == rows
      redirect_to instructors_path
    end
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
  end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to @instructor, notice: 'Instructor was successfully created.' }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to @instructor, notice: 'Instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_url, notice: 'Instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
      params.require(:instructor).permit(:fname, :lname, :rank)
    end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<%= form_for(instructor) do |f| %>
  <% if instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
      <% instructor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>


  <div class="field form-group">
    <%= f.label :rank %>
    <%= f.number_field :rank, class: 'form-control' %>
  </div>

  <div class="actions form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/instructors/edit.html.erb
<h1>Editing Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Show', @instructor %> |
<%= link_to 'Back', instructors_path %>

app/views/instructors/import.html.erb
<%= form_tag({:action => :to_db}, multipart: true, class: 'form') do %>
    <div class="field form-group">
      <%= file_field_tag :file, class: 'form-control' %>
      <%= submit_tag( "Import", class: 'form-control' ) %>
    </div>
<% end %>

app/views/instructors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Instructors</h1>

<table>
  <thead>
    <tr>
      <th>Fname</th>
      <th>Lname</th>
      <th>Rank</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instructors.each do |instructor| %>
      <tr>
        <td><%= instructor.fname %></td>
        <td><%= instructor.lname %></td>
        <td><%= instructor.rank %></td>
        <td><%= link_to 'Show', instructor %></td>
        <td><%= link_to 'Edit', edit_instructor_path(instructor) %></td>
        <td><%= link_to 'Destroy', instructor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instructor', new_instructor_path %>

app/views/instructors/new.html.erb
<h1>New Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Back', instructors_path %>

app/views/instructors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fname:</strong>
  <%= @instructor.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @instructor.lname %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @instructor.rank %>
</p>

<%= link_to 'Edit', edit_instructor_path(@instructor) %> |
<%= link_to 'Back', instructors_path %>