config/routes.rb
Rails.application.routes.draw do
  get 'courses/import', to: 'courses#import', as: 'courses_import'
  get 'students/import', to: 'students#import', as: 'import_students'
  get 'instructors/import', to: 'instructors#import', as: 'instructors_import'
  get 'colleges/import', to: 'colleges#import', as: 'colleges_import'
  get 'high_schools/import', to: 'high_schools#import', as: 'high_schools_import'

  post '/courses(.:format)', to: 'courses#to_db', as: 'course_to_db'
  post '/students(.:format)', to: 'students#to_db', as: 'student_to_db'
  post '/instructors(.:format)', to: 'instructors#to_db', as: 'instructor_to_db'
  post '/colleges(.:format)', to: 'colleges#to_db', as: 'college_to_db'
  post '/high_schools(.:format)', to: 'high_schools#to_db', as: 'high_school_to_db'
  
  get '/courses/stats', to: 'courses#stat', as: 'courses_stat'
  
  get '/student/courses/:id', to: 'students#course', as: 'student_courses'
  get 'course/:id', to: 'courses#more', as: 'more'

  
  devise_for :users
  resources :course_students
  resources :colleges
  resources :high_schools
  resources :instructors
  resources :states
  resources :statistics
  resources :students
  resources :courses

  get 'reports/students/attempts', to: 'student_reports#attempts', as: 'attempt_report'
  get 'users', to: 'users#index', as: 'admin_users'
  root to: 'test#index'
end

app/models/college.rb
class College < ApplicationRecord
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  require 'csv'
  before_action :set_college, only: [:show, :edit, :update, :destroy]

  # GET /colleges
  # GET /colleges.json
  def index
    @colleges = College.all
  end

  # GET /colleges/1
  # GET /colleges/1.json
  def show
  end

  def import
  end

  def to_db
    college = College.new()
    added_rows = 0
    rows=0
    CSV.foreach(params[:file].path, :headers => true) do |row|
      data = row.to_hash
      
      college = College.new(
                         :city => data['City'],
                         :state => (data['State']),
                         :name => data['Name'],
                         :uid => (data['UID']),
                         :county => data['County']
      )
      if college.save
        added_rows = added_rows + 1
      end
      rows = rows + 1
    end
    if added_rows == rows
      redirect_to colleges_path
    end
  end

  # GET /colleges/new
  def new
    @college = College.new
  end

  # GET /colleges/1/edit
  def edit
  end

  # POST /colleges
  # POST /colleges.json
  def create
    @college = College.new(college_params)

    respond_to do |format|
      if @college.save
        format.html { redirect_to @college, notice: 'College was successfully created.' }
        format.json { render :show, status: :created, location: @college }
      else
        format.html { render :new }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colleges/1
  # PATCH/PUT /colleges/1.json
  def update
    respond_to do |format|
      if @college.update(college_params)
        format.html { redirect_to @college, notice: 'College was successfully updated.' }
        format.json { render :show, status: :ok, location: @college }
      else
        format.html { render :edit }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colleges/1
  # DELETE /colleges/1.json
  def destroy
    @college.destroy
    respond_to do |format|
      format.html { redirect_to colleges_url, notice: 'College was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_college
      @college = College.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def college_params
      params.require(:college).permit(:city, :state, :name, :uid, :county)
    end
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/views/colleges/_form.html.erb
<%= form_for(college) do |f| %>
  <% if college.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(college.errors.count, "error") %> prohibited this college from being saved:</h2>

      <ul>
      <% college.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :uid %>
    <%= f.text_field :uid %>
  </div>

  <div class="field">
    <%= f.label :county %>
    <%= f.text_field :county %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/colleges/edit.html.erb
<h1>Editing College</h1>

<%= render 'form', college: @college %>

<%= link_to 'Show', @college %> |
<%= link_to 'Back', colleges_path %>

app/views/colleges/import.html.erb
<%= form_tag({:action => :to_db}, multipart: true, class: 'form') do %>
    <div class="field form-group">
      <%= file_field_tag :file, class: 'form-control' %>
      <%= submit_tag( "Import", class: 'form-control' ) %>
    </div>
<% end %>

app/views/colleges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Colleges</h1>

<table>
  <thead>
    <tr>
      <th>City</th>
      <th>State</th>
      <th>Name</th>
      <th>Uid</th>
      <th>County</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colleges.each do |college| %>
      <tr>
        <td><%= college.city %></td>
        <td><%= college.state %></td>
        <td><%= college.name %></td>
        <td><%= college.uid %></td>
        <td><%= college.county %></td>
        <td><%= link_to 'Show', college %></td>
        <td><%= link_to 'Edit', edit_college_path(college) %></td>
        <td><%= link_to 'Destroy', college, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New College', new_college_path %>

app/views/colleges/new.html.erb
<h1>New College</h1>

<%= render 'form', college: @college %>

<%= link_to 'Back', colleges_path %>

app/views/colleges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
  <%= @college.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @college.state %>
</p>

<p>
  <strong>Name:</strong>
  <%= @college.name %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @college.uid %>
</p>

<p>
  <strong>County:</strong>
  <%= @college.county %>
</p>

<%= link_to 'Edit', edit_college_path(@college) %> |
<%= link_to 'Back', colleges_path %>