config/routes.rb
Rails.application.routes.draw do
  get 'courses/import', to: 'courses#import', as: 'courses_import'
  get 'students/import', to: 'students#import', as: 'import_students'
  get 'instructors/import', to: 'instructors#import', as: 'instructors_import'
  get 'colleges/import', to: 'colleges#import', as: 'colleges_import'
  get 'high_schools/import', to: 'high_schools#import', as: 'high_schools_import'

  post '/courses(.:format)', to: 'courses#to_db', as: 'course_to_db'
  post '/students(.:format)', to: 'students#to_db', as: 'student_to_db'
  post '/instructors(.:format)', to: 'instructors#to_db', as: 'instructor_to_db'
  post '/colleges(.:format)', to: 'colleges#to_db', as: 'college_to_db'
  post '/high_schools(.:format)', to: 'high_schools#to_db', as: 'high_school_to_db'
  
  get '/courses/stats', to: 'courses#stat', as: 'courses_stat'
  
  get '/student/courses/:id', to: 'students#course', as: 'student_courses'
  get 'course/:id', to: 'courses#more', as: 'more'

  
  devise_for :users
  resources :course_students
  resources :colleges
  resources :high_schools
  resources :instructors
  resources :states
  resources :statistics
  resources :students
  resources :courses

  get 'reports/students/attempts', to: 'student_reports#attempts', as: 'attempt_report'
  get 'users', to: 'users#index', as: 'admin_users'
  root to: 'test#index'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  require 'csv'
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  def more
    @courses = CourseStudent.where(course_id: params[:id])
    @num_a = @courses.where(grade: 'A').count
    @num_b = @courses.where(grade: 'B').count
    @num_c = @courses.where(grade: 'C').count
    @num_d = @courses.where(grade: 'D').count
    @num_f = @courses.where(grade: 'F').count
    @num_w = @courses.where(grade: 'W').count
    @passed = @num_a + @num_b + @num_c
    @faile = @num_d + @num_f
  end
  def stat
    @courses = Course.all
    @num_courses = @courses.count
    @num_intr = Course.all.group_by(&:instructor_id)
  end

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all.paginate(:page => params[:page])
    if params[:search]
      @courses = Course.search(params[:search]).order("created_at DESC")
    else
      @courses = Course.all.order("created_at DESC")
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import

  end

  def to_db
    course = Course.new()
    added_rows = 0
    rows=0
    CSV.foreach(params[:file].path, :headers => true) do |row|
      data = row.to_hash
      instr = Instructor.find_by(name: data['Instructor'])
      if instr.blank?
        instr_id = (Instructor.create(:name => data['Instructor'])).id
      else
        instr_id = instr.id
      end
      #byebug
      course = Course.new(
                         :term => (data['Term']).to_i,
                         :rubric => data['Prefix'],
                         :course_number => (data['Number']).to_i,
                         :section => data['Sect'],
                         :credit_hours => (data['Credit']).to_i,
                         :day => data['Days'],
                         :time => data['Start'],
                         :instructor => data['Instructor'],
                         :course_type => data['Type'],
                         :instructor_id => instr_id.to_i
      )
      if course.save
        added_rows = added_rows + 1
      end
      rows = rows + 1
    end
    if added_rows == rows
      redirect_to courses_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:term, :rubric, :course_number, :section, :credit_hours, :course_type, :day, :time, :instructor, :instructor_rank)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(course) do |f| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :term %>
    <%= f.number_field :term, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :rubric %>
    <%= f.text_field :rubric, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :course_number %>
    <%= f.number_field :course_number, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :section %>
    <%= f.text_field :section, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :credit_hours %>
    <%= f.number_field :credit_hours, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :course_type %>
    <%= f.text_field :course_type, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :day %>
    <%= f.text_field :day, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :time %>
    <%= f.text_field :time, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :instructor %>
    <%= f.text_field :instructor, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :instructor_rank %>
    <%= f.text_field :instructor_rank, class: 'form-control' %>
  </div>

  <div class="actions form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<div class="col-md-12">
  <p id="notice"><%= notice %></p>

  <h1>Courses</h1>

  <%= form_tag(courses_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Courses" %>
  <%= submit_tag "Search", :name => nil %>
  <% end %>
  <% if @courses.blank? %>
  <h4>There are no courses containing the term <%= params[:search] %>.</h4>
  <% end %>

  <table class="table table-striped table-responsive">
    <thead>
    <tr>
      <th>Term</th>
      <th>Rubric</th>
      <th>Number</th>
      <th>Sect.</th>
      <th>Hours</th>
      <th>Type</th>
      <th>Day</th>
      <th>Time</th>
      <th>Instr.</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @courses.each do |course| %>
        <tr>
          <td><%= course.term %></td>
          <td><%= course.rubric %></td>
          <td><%= link_to course.course_number,more_path(course.id) %></td>
          <td><%= course.section %></td>
          <td><%= course.credit_hours %></td>
          <td><%= course.course_type %></td>
          <td><%= course.day %></td>
          <td><%= course.time %></td>
          <td><%= course.instructor %></td>
          <td><b><u><%= link_to 'Show', course %></u></b></td>
          <td><b><u><%= link_to 'Edit', edit_course_path(course) %></u></b></td>
          <td><b><u><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></u></b></td>
        </tr>
    <% end %>
    </tbody>
  </table>
  
  <br>

  <%= link_to 'New Course', new_course_path %>
</div>

app/views/courses/more.html.erb
<div class="col-md-12">
  <p><%= 'Number of A: ' + @num_a.to_s %></p>
  <p><%= 'Number of B: ' + @num_b.to_s %></p>
  <p><%= 'Number of C: ' + @num_c.to_s %></p>
  <p><%= 'Number of D: ' + @num_d.to_s %></p>
  <p><%= 'Number of F: ' + @num_f.to_s %></p>
  <p><%= 'Number of W: ' + @num_w.to_s %></p>
  <p><%= 'Number of passed Students: ' + @passed.to_s %></p>
  <p><%= 'Number of failed Students: ' + (@num_d + @num_f).to_s %></p>
</div>

app/views/courses/new.html.erb
<div class="col-md-12">

<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>
</div>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Term:</strong>
  <%= @course.term %>
</p>

<p>
  <strong>Rubric:</strong>
  <%= @course.rubric %>
</p>

<p>
  <strong>Course number:</strong>
  <%= @course.course_number %>
</p>

<p>
  <strong>Section:</strong>
  <%= @course.section %>
</p>

<p>
  <strong>Credit hours:</strong>
  <%= @course.credit_hours %>
</p>

<p>
  <strong>Course type:</strong>
  <%= @course.course_type %>
</p>

<p>
  <strong>Day:</strong>
  <%= @course.day %>
</p>

<p>
  <strong>Time:</strong>
  <%= @course.time %>
</p>

<p>
  <strong>Instructor:</strong>
  <%= @course.instructor %>
</p>

<p>
  <strong>Instructor rank:</strong>
  <%= @course.instructor_rank %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/courses/stat.html.erb
<div class="col-md-12">
  <div class="row top_tiles">
    <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
      <div class="tile-stats">
        <div class="icon"><i class="fa fa-caret-square-o-right"></i></div>
        <div class="count"><%= @num_courses %></div>
        <h3>Number Courses </h3>
        <p>Total courses.</p>
      </div>
    </div>

    <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
      <div class="tile-stats">
        <div class="icon"><i class="fa fa-caret-square-o-right"></i></div>
        <div class="count">1</div>
        <h3>Courses </h3>
        <p>Lorem ipsum psdea itgum rixt.</p>
      </div>
    </div>

    <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
      <div class="tile-stats">
        <div class="icon"><i class="fa fa-caret-square-o-right"></i></div>
        <div class="count">1</div>
        <h3>Instructors </h3>
        <p>Lorem ipsum psdea itgum rixt.</p>
      </div>
    </div>

    <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
      <div class="tile-stats">
        <div class="icon"><i class="fa fa-caret-square-o-right"></i></div>
        <div class="count">1</div>
        <h3>Users </h3>
        <p>Lorem ipsum psdea itgum rixt.</p>
      </div>
    </div>

  </div>
</div>
<div class="col-md-12">
  <table class="table table-striped table-responsive">
    <thead>
    <tr>
      <th>Term</th>
      <th>Rubric</th>
      <th>Number</th>
      <th>Sect.</th>
      <th>passed</th>
      <th>failed</th>
      <th>withdrew</th>
    </tr>
    </thead>

    <tbody>
    <% @courses.each do |course| %>
        <tr>
          <td><%= course.term %></td>
          <td><%= course.rubric %></td>
          <td><%= course.course_number %></td>
          <td><%= course.section %></td>
          <td><%= CourseStudent.where("grade != 'F' AND grade != 'W' And course_id ="+course.id.to_s).count %></td>
          <td><%= CourseStudent.where("grade = 'F'  And course_id ="+course.id.to_s).count %></td>
          <td><%= CourseStudent.where("grade = 'W' And course_id ="+course.id.to_s).count %></td>
    <% end %>
    </tbody>
  </table>
</div>